{{- range $workloadKey, $workload := mustMerge (dict) (default (dict) .Values.deployment) (default (dict) .Values.statefulSet) -}}
{{- if and $workload.autoscaling $workload.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "app.fullname" $) $workloadKey }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with $workload.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ ternary "Deployment" "StatefulSet" (hasKey $.Values.deployment $workloadKey) }}
    name: {{ printf "%s-%s" (include "app.fullname" $) $workloadKey }}
  minReplicas: {{ $workload.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ required "maxReplicas field is required for workload autoscaling!" $workload.autoscaling.maxReplicas }}
{{- with $workload.autoscaling.metrics }}
  metrics:
    {{- if kindIs "string" . }}
    {{- tpl . $ | nindent 4 }}
    {{- else }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- with $workload.autoscaling.behavior }}
  behavior:
    {{- if kindIs "string" . }}
    {{- tpl . $ | nindent 4 }}
    {{- else }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
---
{{- end }}
{{- end }}